### ISSUE TITLE
could you please provide the dataset of api_rawdata and mashup_rawdata，thank you very much!

### ISSUE THREAD

**Issue by rubbish123** [thuymo87/Doc2Vec-NLP-model-for-mashup-API-descriptions#1]

**Comment by thuymo87** [comment]
Hi 
The raw data sets are already in the repository.

**Comment by rubbish123** [comment]
I'm so sorry to bother you, this issue should have been sent to 
"AMF---Attentional-Matrix-Factorization-with-Context-and-Co-invocation-for-service-recommendation" repository.
I realized I had sent the wrong one, so I closed this issue and went to that repository to send it again. The code file in that repository need to read data from "api_rawdata.csv" and "mashup_rawdata.csv", but that repository doesn't have the required files, so could you please provide the dataset? Thank you very much!

**Comment by rubbish123** [comment]
I'm so sorry to bother you, this issue should have been sent to
"AMF---Attentional-Matrix-Factorization-with-Context-and-Co-invocation-for-service-recommendation" repository.
I realized I had sent the wrong one, so I closed this issue and went to that repository to send it again. The code file in that repository need to read data from "api_rawdata.csv" and "mashup_rawdata.csv", but that repository doesn't have the required files, so could you please provide the dataset? Thank you very much!
